### ISSUE TITLE
Trop de trains affichés

### ISSUE THREAD

**Issue by batnyu** [vivienlouradour/spring-informationgare#4]
Si le catalogue nous envoie tous les trains de la journée, on est dans la merde pour les afficher tous et il y en a qui sont inutile d'afficher. Il faudrait restreindre en prenant que les trains dont le temps d'arrivée/départ est inférieur à (maintenant + 6 heures)

**Comment by vivienlouradour** [comment]
done, cf : [commit](https://github.com/vivienlouradour/spring-informationgare/commit/bce3650d858bb55df25b96a9f03f7a7722f53bdd)
